apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python9524github
  janus-idp.io/tekton: python9524github
  backstage.io/kubernetes-id: python9524github
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python9524github
resources:
- deployment.yaml
- route.yaml
- service.yaml
