apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python9524github
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python9524github 
  name: python9524github
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python9524github 
